"""Gateway registry example generation for the Yeisme fork.

Builds the sanitized, script-generated registry example consumed by the
onboarding journey. The builder derives the ``exposeTools`` whitelist from
:mod:`blender_mcp.tool_classification`, so generate/exec tools are
structurally excluded (the builder raises before emitting YAML if one ever
appears), and refuses to emit anything that looks like a credential or a
user-specific path.

Output shapes:

- *fragment*: just the ``servers:`` block, for pasting into an existing
  user-level registry (``~/.mcp-gateway/registry.yaml``).
- *full example*: a complete minimal registry (``version``/``gateway``/
  ``servers``) that ``mcp-gateway config validate --registry <file>``
  accepts standalone.
"""

from __future__ import annotations

import re

from blender_mcp import tool_classification as tc

NAMESPACE = "blender"
SERVER_KEY = "blender"
SERVER_COMMAND = "uvx"
SERVER_ARGS = ["blender-mcp"]
SERVER_DESCRIPTION = (
    "Local Blender execution backend (loopback addon socket); read + curated "
    "write tools only, generate/exec excluded by the generator"
)

# Loopback-only demonstration values for the standalone full example. These
# are placeholders, not endpoints of any real deployment.
EXAMPLE_GATEWAY_HOST = "127.0.0.1"
EXAMPLE_GATEWAY_PORT = 8080

#: Patterns that must never appear in a generated example. Keeping this list
#: conservative is fine: the generator only emits values we control.
SANITIZATION_PATTERNS: tuple[tuple[str, str], ...] = (
    (r"(?i)\b(api[_-]?key|secret|password|passwd|token)\b\s*[:=]\s*\S", "credential-like key/value"),
    (r"/home/[A-Za-z0-9_.-]+", "absolute home path"),
    (r"/Users/[A-Za-z0-9_.-]+", "absolute home path"),
    (r"(?i)[A-Za-z]:\\\\", "absolute windows path"),
    (r"https?://(?!127\.0\.0\.1\b|localhost\b)\S+", "non-loopback URL"),
)


def assert_sanitized(text: str) -> None:
    """Raise ``ValueError`` when ``text`` contains unsafe material."""
    for pattern, label in SANITIZATION_PATTERNS:
        match = re.search(pattern, text)
        if match:
            raise ValueError(
                f"generated example failed sanitization ({label}): {match.group(0)!r}"
            )


def export_tools() -> list[str]:
    """The generated whitelist: read + curated write, never generate/exec.

    Applies its own exportability guard rather than trusting the caller's
    list construction, so a tampered whitelist still cannot reach YAML.
    """
    tools = tc.default_export_tools()
    tc.assert_exportable(tools)
    return tools


def build_server_yaml(indent: str = "  ") -> str:
    """Render the ``servers:`` block for the blender backend."""
    tools = export_tools()
    lines = [
        "servers:",
        f"{indent}{SERVER_KEY}:",
        f"{indent}  enabled: true",
        f"{indent}  description: {SERVER_DESCRIPTION}",
        f"{indent}  transport: stdio",
        f"{indent}  command: {SERVER_COMMAND}",
        f"{indent}  args: [{SERVER_ARGS[0]}]",
        f"{indent}  gateway:",
        f"{indent}    enabled: true",
        f"{indent}    namespace: {NAMESPACE}",
        f"{indent}    exposeTools:",
    ]
    lines.extend(f"{indent}      - {tool}" for tool in tools)
    return "\n".join(lines) + "\n"


def build_fragment() -> str:
    """The paste-in ``servers:`` fragment for an existing user registry."""
    text = build_server_yaml()
    assert_sanitized(text)
    return text


def build_full_example() -> str:
    """A standalone minimal registry accepted by ``mcp-gateway config validate``."""
    header = "\n".join(
        [
            "# Generated by scripts/generate_gateway_registry_example.py -- do not edit.",
            "# Sanitized example: loopback gateway placeholders, no credentials,",
            "# generate/exec tools structurally excluded from exposeTools.",
            "version: 1",
            "gateway:",
            f"  host: {EXAMPLE_GATEWAY_HOST}",
            f"  port: {EXAMPLE_GATEWAY_PORT}",
            f"  publicUrl: http://{EXAMPLE_GATEWAY_HOST}:{EXAMPLE_GATEWAY_PORT}",
        ]
    )
    text = header + "\n" + build_server_yaml()
    assert_sanitized(text)
    return text


def validate_with_gateway_cli(path: str, binary: str = "mcp-gateway") -> tuple[bool, str]:
    """Run ``mcp-gateway config validate`` against a generated example.

    Returns ``(ok, combined_output)``. Raises FileNotFoundError when the CLI
    is not installed locally; callers decide whether that is fatal or a skip.
    """
    import shutil
    import subprocess

    if shutil.which(binary) is None:
        raise FileNotFoundError(f"{binary} not found on PATH")
    proc = subprocess.run(
        [binary, "config", "validate", "--registry", path],
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    output = (proc.stdout + proc.stderr).strip()
    return proc.returncode == 0, output
