"""Tests for the generated Gateway registry example (task 1.2)."""

from __future__ import annotations

import pytest

from blender_mcp import gateway_registry as gr
from blender_mcp import tool_classification as tc

EXAMPLE_PATH = pytest.importorskip("pathlib").Path(__file__).resolve().parents[1] / (
    "docs/gateway/registry-blender-example.yaml"
)


class TestExampleContent:
    def test_checked_in_example_matches_regeneration(self):
        assert EXAMPLE_PATH.exists(), "docs/gateway/registry-blender-example.yaml missing"
        assert EXAMPLE_PATH.read_text(encoding="utf-8") == gr.build_full_example()

    def test_example_is_sanitized(self):
        gr.assert_sanitized(gr.build_full_example())
        gr.assert_sanitized(gr.build_fragment())

    def test_generate_and_exec_never_in_expose_list(self):
        tools = gr.export_tools()
        for tool in tc.tools_for_level("generate") + tc.tools_for_level("exec"):
            assert tool not in tools

    def test_all_exposed_tools_are_read_or_write(self):
        levels = {tc.TOOL_CLASSIFICATION[tool] for tool in gr.export_tools()}
        assert levels <= {"read", "write"}

    def test_exposure_within_gateway_public_tool_cap(self):
        assert len(gr.export_tools()) <= tc.GATEWAY_MAX_PUBLIC_TOOLS

    def test_fragment_mentions_all_exposed_tools(self):
        fragment = gr.build_fragment()
        for tool in gr.export_tools():
            assert f"- {tool}" in fragment

    def test_fragment_has_namespace_and_stdio_command(self):
        fragment = gr.build_fragment()
        assert "namespace: blender" in fragment
        assert "transport: stdio" in fragment
        assert "command: uvx" in fragment

    def test_full_example_has_required_toplevel_fields(self):
        example = gr.build_full_example()
        assert example.startswith("# Generated by scripts/generate_gateway_registry_example.py")
        assert "version: 1" in example
        assert "servers:" in example


class TestSanitizationGuard:
    def test_credential_like_content_rejected(self):
        with pytest.raises(ValueError, match="sanitization"):
            gr.assert_sanitized("servers:\n  x:\n    api_key: abc123\n")

    def test_home_path_rejected(self):
        with pytest.raises(ValueError, match="sanitization"):
            gr.assert_sanitized("workDir: /home/alice/scratch\n")

    def test_non_loopback_url_rejected(self):
        with pytest.raises(ValueError, match="sanitization"):
            gr.assert_sanitized("url: https://internal.example.com/mcp\n")

    def test_loopback_url_allowed(self):
        gr.assert_sanitized("publicUrl: http://127.0.0.1:8080\n")


class TestGeneratorGuardrails:
    def test_generator_refuses_exec_tool_injection(self, monkeypatch):
        # Even if the default whitelist were tampered with, the builder must
        # refuse to emit exec tools.
        monkeypatch.setattr(
            tc, "default_export_tools",
            lambda: ["get_scene_info", "execute_blender_code"],
        )
        with pytest.raises(ValueError, match="non-exportable"):
            gr.export_tools()

    def test_generator_refuses_generate_tool_injection(self, monkeypatch):
        monkeypatch.setattr(
            tc, "default_export_tools",
            lambda: ["generate_hunyuan3d_model"],
        )
        with pytest.raises(ValueError, match="non-exportable"):
            gr.export_tools()


class TestGatewayCliValidation:
    def test_example_passes_mcp_gateway_validate(self):
        pytest.importorskip("shutil")
        import shutil
        import tempfile
        from pathlib import Path

        if shutil.which("mcp-gateway") is None:
            pytest.skip("mcp-gateway CLI not installed")

        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "registry.yaml"
            path.write_text(gr.build_full_example(), encoding="utf-8")
            ok, output = gr.validate_with_gateway_cli(str(path))
        assert ok, output
        assert "Config valid" in output

    def test_cli_validation_rejects_broken_registry(self):
        import shutil
        import tempfile
        from pathlib import Path

        if shutil.which("mcp-gateway") is None:
            pytest.skip("mcp-gateway CLI not installed")

        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "registry.yaml"
            path.write_text("version: 2\nservers: {}\n", encoding="utf-8")
            ok, _output = gr.validate_with_gateway_cli(str(path))
        assert not ok
